### ISSUE TITLE
link hook: factory-made modules

### ISSUE THREAD

**Issue by jorendorff** [jorendorff/js-loaders#19]
We should discuss this because I'm not confident I understand it.

If .exports is present, do we have to do link-time checking (on ES6 modules that import the factory-made module) before calling the .execute hook?

I think Dave said that if .exports is missing, the module is dynamically linked? I don't understand what problem that's solving?

Dave also said something about someone figuring out a way for import cycles to be allowed between factory-made modules, but I don't see it yet.

**Comment by dherman** [comment]
I think we don't have a very compelling rationale for the `.exports` case -- if you want static linking the core system already gives you that; the dynamic linking is there for AMD/CommonJS compatibility. But the only thing I can see you getting from the `.exports` mechanism is a somewhat more convenient way to programmatically specify the contents of a module, which you could otherwise provide via the `.translate` hook and compilation.

**Comment by dherman** [comment]
The semantics of the dynamic linking is, roughly:
1. all non-AMD-style modules get statically linked, registered, and executed
2. those modules are passed into the factory function(s) for AMD style modules
3. AMD style modules are executed, converted to Module instance objects, linked
4. recur

Note that AMD style modules in one iteration of this process are themselves passed as squishy objects and can be mutated; they are only converted to Module instance objects just before registering.

**Comment by dherman** [comment]
Didn't state (1) very clearly: because no cycles are allowed between all-AMD SCC's and all-ES6 SCC's, you sort in dependency order and start at the leaves and work your way up.

**Comment by samth** [comment]
See also issue #17 about when the results of the link hook are committed.

**Comment by jorendorff** [comment]
This is fixed in the linking spec text.
