### ISSUE TITLE
DEFAULT RESOLVE BEHAVIOR VS. CONCATENATION

### ISSUE THREAD

**Issue by samth** [jorendorff/js-loaders#6]
P1 ISSUE: DEFAULT RESOLVE BEHAVIOR VS. CONCATENATION. Consider a
module "a/b/c", in two different scenarios:
1. loaded as a module from http://js.com/scripts/a/b/c.js
2. defined in a script loaded from http://js.com/scripts/all.js
which contains several modules.
It is the same module "a/b/c" either way. It contains:

```
import "x" as x;
```

which triggers these resolve hook calls:

``` js
// case 1
loader.resolve("x", { referer: { name: "a/b/c",
                                 url: "http://example.com/scripts/a/b/c.js" }})
// case 2
loader.resolve("x", {  referer: {name: "a/b/c",
                                 url: "http://example.com/scripts/all.js"}})
```

It is hard to imagine these two calls (or whatever else the default
behavior is) returning the same URL for x, which is too bad if we
want to support concatenation. Perhaps a Referer object should also
contain a .type property? :-P

https://github.com/jorendorff/js-loaders/blob/master/loaders.js#L1453

**Comment by dherman** [comment]
> It is hard to imagine these two calls...returning the same URL for x

But in fact that's exactly what the default behavior will do. In particular, the default behavior doesn't make use of the referer's `.url` property. Since `"x"` was requested, it gets the top-level `"x"` module; if `"./x"` had been requested, it would get the `"a/b/x"` module; but either way, the `.url` property is not consulted.

A custom hook, of course, can use the information handed to it to behave as arbitrarily differently as it wants. It can even consult `Math.random()` or `Date.now()` if it likes... ;-P

Dave

**Comment by jorendorff** [comment]
Got it, I was really confused.
